### ISSUE TITLE
Add dataset(s) to repository

### ISSUE THREAD

**Issue by jeff1evesque** [ahyman3/IST-718-BDA#3]
We need to add our dataset(s) to this repository, and adjust our code respectively.

**Comment by jeff1evesque** [comment]
Committing ~3.8GB to a git repository is too strenuous on the git history. Specifically, this would mean that each branch, or commit would need to clunk around some compounding ~3.8GB of history each time something small or large is committed to the repository. So, we looked at storing each item in dropbox.  This was estimated to take ~15 hours. However, adding many small files over a network to a remote location, will be [significantly slower](https://blog.webernetz.net/network-transfer-1-big-vs-100-small-files/) than adding one large file. Therefore, we'll add one large zip file to [dropbox](https://www.dropbox.com/sh/alwb4sr9941gtlk/AABKkc8lW_X37P2I3fpibUcfa?dl=0). This approach took roughly 20 minutes.

**Comment by jeff1evesque** [comment]
Overall, storing this dataset on dropbox, allows us to have control and access without login to kaggle. Since this issue no longer involves version controlling files, I'll close this issue. We may consider adjusting our python code, to download, and unzip the corresponding dataset(s). Then, we'll need to determine whether to send the unzipped files to a database, or directly process the data. Since the same issues will exist regarding the [network connection](https://blog.webernetz.net/network-transfer-1-big-vs-100-small-files/), we'll likely need to download + unzip directly on the machine with the database, or the machine performing the computation directly (without a database).

**Comment by ahyman3** [comment]
Have you looked more into using an s3 bucket for the files? I think it is [cheap enough](https://aws.amazon.com/s3/pricing/?nc=sn&loc=4) ($0.0004 per 1000 GET requests, storage space available)

**Comment by jeff1evesque** [comment]
I looked into that a bit, just haven't logged my findings on #2.
